### ISSUE TITLE
Can't use SpringBoot base URL

### ISSUE THREAD

**Issue by c0c0n3** [IDSIA/adapquest#25]
### Problem
I'd like make Adaptive Questionnaire serve its UI from a configurable root URL path. For example, given the root path of `/aq`, Adaptive Questionnaire would serve its home from `/aq/`, CSS would be at `/aq/css/style.css`, and so on. SpringBoot applications support this kind of setup through the `server.servlet.context-path` application property. But when I try using that property as in e.g. `server.servlet.context-path=/aq`, the UI breaks. The home page loads, but all its links are relative to `/` instead of the configured root path, e.g. `/aq`, so the browser can't fetch any dependent resources like JS, CSS, etc.

### Steps to reproduce
1. Set an env var like so: `server_servlet_context-path=/aq`
2. Start Adaptive Questionnaire in the same terminal.
3. Browse to `localhost:8080`, you should get a 404 since the configured root path is `/aq`.
4. But when you browse to `localhost:8080/aq`, the home page doesn't display properly because the links in the HTML aren't prefixed with `/aq`. For example, `<link rel="stylesheet" href="/css/style.css">` instead of `<link rel="stylesheet" href="/aq/css/style.css">`, `<a href="/demo/" class="btn btn-primary">Go to Demo</a>` instead of `<a href="/aq/demo/" class="btn btn-primary">Go to Demo</a>`, and so on.

### Notes
It looks like the Thymeleaf templates use server-relative URLs as in e.g. `fragments/layout.html`

```html
<link rel="stylesheet" th:href="@{~/css/style.css}"/>
```

The templating engine renders those kinds of URL paths as absolute since you might be calling another server app. On the other hand, the templating engine prefixes context-relative URLs like

```html
<link rel="stylesheet" th:href="@{/css/style.css}"/>
```

(notice the missing tilde at the front) with the configured servlet context, so once rendered the link would become

```html
<link rel="stylesheet" href="/aq/css/style.css"/>
```

if you set `server_servlet_context-path=/aq`.

So implementing a solution that honours any configured servlet context could boil down to removing tildes in front of all the URLs in the Thymeleaf templates. Plus, massaging the custom JavaScript in `charts.js`...

**Comment by cbonesana** [comment]
It will be fixed for the next 1.6.3.
