### ISSUE TITLE
Alloy demo survey charts

### ISSUE THREAD

**Issue by c0c0n3** [IDSIA/adapquest#30]
When taking the Alloy demo survey with AQ version `1.6.1.`, there were two charts in the bottom half of the screen to show progress while answering questions. With version `1.6.3` those charts are gone, they only show up again at the end of the survey. Not sure this is a bug, maybe this change was intentional? You can check out version `1.6.3` here:

- https://kitt4sme.collab-cloud.eu/aq

**Comment by cbonesana** [comment]
Charts and plots have been deactivate for the Demo. This is intended and in the direction of having a more realistic user experience.

However, the charts can be restored by adding the query parameter `show=true`.

**Comment by c0c0n3** [comment]
excellent, thanks for clarifying!
